#!/usr/bin/env python3
"""Provision Bebebendle + SVAGA+ production shared secrets on the host.

Run as deploy on production:
  python3 /home/deploy/provision-production-secrets.py

Writes:
  /opt/bebebendle/shared/.env.provisioned
  upserts BEBEBENDLE_INTERNAL_SECRET + SVAGA_TARGET_USER_ID into
  /opt/svagaplus/shared/backend/.env
  /home/deploy/install-bebebendle-env.sh  (sudo once)
  /home/deploy/bebebendle-secrets-summary.txt

Never prints secret values.
"""
from __future__ import annotations

import os
import secrets
import subprocess
from hashlib import sha256
from pathlib import Path

SVAGA_ENV = Path("/opt/svagaplus/shared/backend/.env")
BEBE_READY = Path("/opt/bebebendle/shared/.env.provisioned")
DB_ONCE = Path("/home/deploy/bebebendle-db-pass-once.txt")
SUMMARY = Path("/home/deploy/bebebendle-secrets-summary.txt")
INSTALL_SH = Path("/home/deploy/install-bebebendle-env.sh")

# Olesha on production SVAGA+ (users.username = olesha)
SVAGA_TARGET_USER_ID = "f0d5662b-0ca2-4d8b-bde4-5e5897f36549"


def rand_hex(n_bytes: int = 32) -> str:
    return secrets.token_hex(n_bytes)


def rand_urlsafe(n_bytes: int = 18) -> str:
    return secrets.token_urlsafe(n_bytes)


def parse_env(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        out[key.strip()] = value
    return out


def render_env(
    order: list[str],
    data: dict[str, str],
    comments: dict[str, str] | None = None,
) -> str:
    comments = comments or {}
    lines: list[str] = [
        "# Bebebendle PRODUCTION — generated by provision-production-secrets.py",
        "# Do not commit. Mode 600. Owner deploy:deploy.",
        "",
    ]
    for key in order:
        if key in comments:
            lines.append("# " + comments[key])
        lines.append(f"{key}={data.get(key, '')}")
    for key, value in data.items():
        if key not in order:
            lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)


def upsert_keys(path: Path, updates: dict[str, str]) -> list[str]:
    actions: list[str] = []
    text = path.read_text() if path.exists() else ""
    lines = text.splitlines()
    keys_seen: set[str] = set()
    new_lines: list[str] = []
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
            new_lines.append(line)
            continue
        key = line.split("=", 1)[0].strip()
        if key in updates:
            new_lines.append(f"{key}={updates[key]}")
            keys_seen.add(key)
            actions.append(f"updated {key}")
        else:
            new_lines.append(line)
    missing = [key for key in updates if key not in keys_seen]
    if missing:
        if new_lines and new_lines[-1].strip():
            new_lines.append("")
        new_lines.append("# --- Bebebendle integration (provisioned) ---")
        for key in missing:
            new_lines.append(f"{key}={updates[key]}")
            actions.append(f"appended {key}")
    path.write_text("\n".join(new_lines) + "\n")
    path.chmod(0o600)
    return actions


def is_filled(value: str) -> bool:
    s = (value or "").strip()
    return bool(s) and "CHANGE_ME" not in s


def main() -> None:
    hop_secret = rand_hex(32)
    bot_internal = rand_hex(32)
    session_secret = rand_hex(32)
    cron_secret = rand_hex(24)
    admin_password = rand_urlsafe(18)

    db_url = ""
    if DB_ONCE.exists():
        for line in DB_ONCE.read_text().splitlines():
            if line.startswith("DATABASE_URL="):
                db_url = line.split("=", 1)[1].strip()
                break

    existing: dict[str, str] = {}
    for candidate in (
        BEBE_READY,
        Path("/home/deploy/bebebendle/shared/.env.example"),
        Path("/opt/bebebendle/shared/.env.example"),
    ):
        if candidate.exists() and os.access(candidate, os.R_OK):
            existing.update(parse_env(candidate.read_text()))

    bot_token = existing.get("BOT_TOKEN", "")
    bot_user = existing.get("NEXT_PUBLIC_TELEGRAM_BOT_USERNAME", "")

    bebe_order = [
        "APP_ENV",
        "NODE_ENV",
        "SESSION_SECRET",
        "DATABASE_URL",
        "REDIS_HOST",
        "REDIS_PORT",
        "REDIS_PASSWORD",
        "SVAGAPLUS_INTERNAL_URL",
        "SVAGAPLUS_INTERNAL_SECRET",
        "SVAGA_TARGET_USER_ID",
        "BEBEBENDLE_INTERNAL_SECRET",
        "BEBEBENDLE_INTERNAL_URL",
        "BOT_TOKEN",
        "NEXT_PUBLIC_TELEGRAM_BOT_USERNAME",
        "ADMIN_PASSWORD",
        "CRON_SECRET",
        "UPLOADS_DIR",
        "PORT",
        "BOT_HEALTH_HOST",
        "BOT_HEALTH_PORT",
    ]

    bebe_data = {
        "APP_ENV": "production",
        "NODE_ENV": "production",
        "SESSION_SECRET": session_secret,
        "DATABASE_URL": db_url
        or "postgresql://bebebendle:CHANGE_ME@127.0.0.1:5432/bebebendle_production",
        "REDIS_HOST": "127.0.0.1",
        "REDIS_PORT": "6379",
        "REDIS_PASSWORD": existing.get("REDIS_PASSWORD", ""),
        "SVAGAPLUS_INTERNAL_URL": "http://127.0.0.1:5016",
        "SVAGAPLUS_INTERNAL_SECRET": hop_secret,
        "SVAGA_TARGET_USER_ID": SVAGA_TARGET_USER_ID,
        "BEBEBENDLE_INTERNAL_SECRET": bot_internal,
        "BEBEBENDLE_INTERNAL_URL": "http://127.0.0.1:3000",
        "BOT_TOKEN": bot_token,
        "NEXT_PUBLIC_TELEGRAM_BOT_USERNAME": bot_user,
        "ADMIN_PASSWORD": admin_password,
        "CRON_SECRET": cron_secret,
        "UPLOADS_DIR": "/opt/bebebendle/shared/uploads",
        "PORT": "3000",
        "BOT_HEALTH_HOST": "127.0.0.1",
        "BOT_HEALTH_PORT": "3011",
    }

    BEBE_READY.parent.mkdir(parents=True, exist_ok=True)
    BEBE_READY.write_text(
        render_env(
            bebe_order,
            bebe_data,
            {
                "SVAGAPLUS_INTERNAL_SECRET": "same value as SVAGA+ BEBEBENDLE_INTERNAL_SECRET",
                "BEBEBENDLE_INTERNAL_SECRET": "bot -> bebe only; different from hop secret",
                "BOT_TOKEN": "REQUIRED: set from BotFather before first deploy",
                "NEXT_PUBLIC_TELEGRAM_BOT_USERNAME": "REQUIRED: bot username without @",
            },
        )
    )
    BEBE_READY.chmod(0o600)

    svaga_actions = upsert_keys(
        SVAGA_ENV,
        {
            "BEBEBENDLE_INTERNAL_SECRET": hop_secret,
            "SVAGA_TARGET_USER_ID": SVAGA_TARGET_USER_ID,
        },
    )

    INSTALL_SH.write_text(
        """#!/usr/bin/env bash
# Install provisioned Bebebendle .env (run once as root)
set -euo pipefail
if [[ ${EUID} -ne 0 ]]; then
  echo "Run: sudo bash /home/deploy/install-bebebendle-env.sh" >&2
  exit 1
fi
SRC="/opt/bebebendle/shared/.env.provisioned"
DST="/opt/bebebendle/shared/.env"
if [[ ! -f "$SRC" ]]; then
  echo "missing $SRC" >&2
  exit 1
fi
if [[ -f "$DST" ]]; then
  cp -a "$DST" "${DST}.bak.$(date +%Y%m%d%H%M%S)"
fi
cp "$SRC" "$DST"
chown deploy:deploy "$DST"
chmod 600 "$DST"
rm -f /opt/bebebendle/shared/..env.swp
echo "Installed $DST as deploy:deploy mode 600"
ls -la "$DST"
echo "If DATABASE_URL is correct, delete: /home/deploy/bebebendle-db-pass-once.txt"
"""
    )
    INSTALL_SH.chmod(0o700)

    filled = {key: is_filled(str(value)) for key, value in bebe_data.items()}
    db_status = "from db-pass-once" if db_url else "MISSING — fill manually"
    bot_status = "SET" if bot_token else "EMPTY — fill before deploy"
    user_status = "SET" if bot_user else "EMPTY — fill before deploy"

    lines = [
        "Bebebendle + SVAGA+ production secret provision",
        "time: " + subprocess.check_output(["date", "-Is"], text=True).strip(),
        "",
        "=== Shared hop (must match) ===",
        "Bebebendle: SVAGAPLUS_INTERNAL_SECRET",
        "SVAGA+:     BEBEBENDLE_INTERNAL_SECRET",
        f"status: generated ({len(hop_secret)} hex chars)",
        f"SVAGA_TARGET_USER_ID: {SVAGA_TARGET_USER_ID} (olesha)",
        "SVAGA env actions: " + ", ".join(svaga_actions),
        "",
        "=== Bebe-only secrets (generated) ===",
        f"SESSION_SECRET: set ({len(session_secret)} hex)",
        f"BEBEBENDLE_INTERNAL_SECRET (bot hop): set ({len(bot_internal)} hex)",
        f"CRON_SECRET: set ({len(cron_secret)} hex)",
        f"ADMIN_PASSWORD: set ({len(admin_password)} chars urlsafe)",
        f"DATABASE_URL: {db_status}",
        "",
        "=== Still required (manual) ===",
        f"BOT_TOKEN: {bot_status}",
        f"NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: {user_status}",
        "",
        "=== Files ===",
        f"provisioned env: {BEBE_READY}",
        f"install script:  {INSTALL_SH}",
        f"SVAGA env:       {SVAGA_ENV}",
        "",
        "=== Next steps ===",
        "1) Fill BOT_TOKEN + NEXT_PUBLIC_TELEGRAM_BOT_USERNAME:",
        f"     nano {BEBE_READY}",
        "2) Install as root:",
        f"     sudo bash {INSTALL_SH}",
        "3) Restart SVAGA backend (root PM2 on this host):",
        "     sudo pm2 restart svagaplus-backend",
        "4) After first Bebe deploy: rm -f /home/deploy/bebebendle-db-pass-once.txt",
        "",
        "=== Note ===",
        "Prod SVAGA release may lack bebebendle_internal route until SVAGA deploy.",
        "Secrets are paired; smoke tests need that endpoint.",
        "",
        "Key fill map:",
    ]
    for key in bebe_order:
        lines.append(f"  {key}: {'ok' if filled.get(key) else 'NEED'}")

    SUMMARY.write_text("\n".join(lines) + "\n")
    SUMMARY.chmod(0o600)
    print(SUMMARY.read_text())

    svaga = parse_env(SVAGA_ENV.read_text())
    bebe = parse_env(BEBE_READY.read_text())
    hop_a = sha256(svaga.get("BEBEBENDLE_INTERNAL_SECRET", "").encode()).hexdigest()[:12]
    hop_b = sha256(bebe.get("SVAGAPLUS_INTERNAL_SECRET", "").encode()).hexdigest()[:12]
    print(f"hop secret fingerprints match: {hop_a == hop_b} ({hop_a})")
    print(
        "target ids match:",
        svaga.get("SVAGA_TARGET_USER_ID") == bebe.get("SVAGA_TARGET_USER_ID"),
    )
    print("DONE")


if __name__ == "__main__":
    main()
