"use server";

import { ActionResult } from "@/lib/action-result";
import { requireRole } from "@/lib/auth-server";
import { createAnnouncement, deleteAnnouncement, listAllAnnouncements, updateAnnouncement, validateAnnouncement } from "@/lib/announcements";
import { writeAuditLog } from "@/lib/moderation-audit";

type ErrorCode = "unauthorized" | "invalid_input" | "not_found" | "failed";
type AnnouncementView = { id: number; title: string; body: string; active: boolean; createdAt: string; updatedAt: string; createdByUserId: number | null };
const view = (row: Awaited<ReturnType<typeof listAllAnnouncements>>[number]): AnnouncementView => ({ ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() });
async function admin(): Promise<ActionResult<{ id: number }, "unauthorized">> { try { const user = await requireRole("admin"); return { ok: true, data: { id: user.id } }; } catch { return { ok: false, code: "unauthorized", message: "Нужна авторизация администратора" }; } }
export async function listAnnouncementsAction(): Promise<ActionResult<AnnouncementView[], ErrorCode>> { const user = await admin(); if (!user.ok) return user; try { return { ok: true, data: (await listAllAnnouncements()).map(view) }; } catch { return { ok: false, code: "failed", message: "Не удалось загрузить список" }; } }
export async function createAnnouncementAction(input: { title: unknown; body: unknown; active?: unknown }): Promise<ActionResult<AnnouncementView, ErrorCode>> { const user = await admin(); if (!user.ok) return user; const valid = validateAnnouncement(input); if (!valid.ok) return { ok: false, code: "invalid_input", message: valid.error }; try { const row = await createAnnouncement({ ...valid, active: typeof input.active === "boolean" ? input.active : true, createdByUserId: user.data.id }); await writeAuditLog({ actorUserId: user.data.id, action: "announcements.create", details: JSON.stringify({ id: row.id, title: row.title }) }); return { ok: true, data: view(row) }; } catch { return { ok: false, code: "failed", message: "Не удалось создать объявление" }; } }
export async function updateAnnouncementAction(input: { id: unknown; title?: unknown; body?: unknown; active?: unknown }): Promise<ActionResult<AnnouncementView, ErrorCode>> { const user = await admin(); if (!user.ok) return user; const id = Number(input.id); if (!Number.isInteger(id) || id < 1) return { ok: false, code: "invalid_input", message: "Некорректный id" }; const patch: { title?: string; body?: string; active?: boolean } = {}; if (input.title !== undefined || input.body !== undefined) { const valid = validateAnnouncement({ title: input.title ?? "", body: input.body ?? "" }); if (!valid.ok) return { ok: false, code: "invalid_input", message: valid.error }; if (input.title !== undefined) patch.title = valid.title; if (input.body !== undefined) patch.body = valid.body; } if (typeof input.active === "boolean") patch.active = input.active; if (Object.keys(patch).length === 0) return { ok: false, code: "invalid_input", message: "Нет изменений" }; try { const row = await updateAnnouncement(id, patch); if (!row) return { ok: false, code: "not_found", message: "Объявление не найдено" }; await writeAuditLog({ actorUserId: user.data.id, action: "announcements.update", details: JSON.stringify({ id, changed: Object.keys(patch) }) }); return { ok: true, data: view(row) }; } catch { return { ok: false, code: "failed", message: "Не удалось сохранить объявление" }; } }
export async function deleteAnnouncementAction(idInput: unknown): Promise<ActionResult<null, ErrorCode>> { const user = await admin(); if (!user.ok) return user; const id = Number(idInput); if (!Number.isInteger(id) || id < 1) return { ok: false, code: "invalid_input", message: "Некорректный id" }; try { if (!(await deleteAnnouncement(id))) return { ok: false, code: "not_found", message: "Объявление не найдено" }; await writeAuditLog({ actorUserId: user.data.id, action: "announcements.delete", details: JSON.stringify({ id }) }); return { ok: true, data: null }; } catch { return { ok: false, code: "failed", message: "Не удалось удалить объявление" }; } }
